export const AppRoutes = {
  // Admin Routes
  HOME: "/",
  FIELDS: "/fields",
  NEWFIELD: "/newField",
  FIELDGROUP:"/fieldGroup",
  NEWFIELDGROUP:"/newFieldGroup",
  PRODUCT: "/product",
  NEWPRODUCT: "/newProduct",
  ADDPRODUCTDETAILS: "/addProductDetails/:id",
  EDITPRODUCTFIELDS: "/editProductfields/:id",
  ASSETS: "/assets",
  ARCHIVEASSETS: "/archiveAssets",
  VIEWASSET: "/viewAsset/:id",
  EDITASSET: "/editAsset/:id",
  REPORTS: "/reports",
  ORGANIZATIONS: "/organizations",
  ORGANIZATIONS_ADMIN: "/organizations-admin",
  NEWORGANIZATION: "/newOrganization",
  MANAGEUSERS: "/manage-users",
  TEMPLATE:"templates",
  PAGE_NOT_FOUND: "*",
  //User Routes
  LOGIN: "/login",
  REGISTER: "/register",
  ALL: "*",
  TEMPLATE: "/template",
  DOMAIN: '/domain',
};
