export const AppRoutes = {
  // Admin Routes
  HOME: "/",
  NEWFIELD: "/newField",
  FIELDGROUP:"/fieldGroup",
  SIGNUP: "/register",
  ADMIN_STATS: "/stats",
  ADMIN_USERS: "/users",
  CATEGORY: "/category",
  DELETE_USERS: "/users/delete/:id",
  DELETE_SUBADMIN: "/subadmin/delete/:id",
  TASKS: "/tasks",
  REPORTS: "/reports",
  ITEMS: "/items",
  ORGANIZATIONREPORT: "/organizationreport",
  TIER2QUIZDETAILS: "/gameDetail",
  ADMINS: "/admins",
  ADD_ADMIN: "/admins/add-admin",
  QUESTIONS: "/all-questions",
  ADD_QUESTIONS: "/questions/add-question",
  CREATE_QUIZ: "/createQuiz",
  SCHEDULE_QUIZ: "/scheduledQuiz",
  CREATE_TEMPLATE: "/createTemplate",
  EDIT_TEMPLATE: "/editTemplate",
  ADMIN_JOIN_ROOM: "/room",
  PAGE_NOT_FOUND: "*",
  //User Routes
  LOGIN: "/login",
  REGISTER: "/register",
  ALL: "*",
  USER_DASHBOARD: "/dashboard",
  USER_JOIN_ROOM: "/room",
  USER_QUIZ_QUESTIONS: "/quiz",
  USER_STATS: "/stats",
  USER_POINTS_TABLE: "/stats/points-listing",
  USER_PROFILE: "/profile",
  USER_PROGRESS_BAR: "/Progressbar",
  TAMBBOLA: "/Tambola",
  CREATE_TAMBOLA: "/createTambola",
  DRAG: "/drag",
  Settings: "/setting",
  Reports_Print: "/print",
  PROFILE: "/profile",
  CREATE_EMBED_QUIZ_PAGE: "/createEmbed",
  CREATE_EMBED_LEADERBOARD_PAGE: "/embedLeaderboard",
  EMBEDED_QUIZ: "/embed/:id/:id",
  TEMPLATE: "/template",
  SUBSCRIPTION: "/subscription",
  ADD_SUBSCRIPTION_PLAN: "/addSubscriptionPlan",
  FEEDBACK_DATA:"/feedback",
};
