// constants.js

const constants = {
    text: 'Text',
    placeholder: 'Placeholder',
    minLength: 'MinLength',
    maxLength: 'MaxLength',
    number: 'Number',
    email: 'Email',
    phone: 'Phone',
    dropdown: 'Dropdown',
    checkbox: 'Checkbox',
    radio: 'Radio',
    multiselect: 'MultiSelect',
    date: 'Date',
    tagNumber: 'Tag number',
    name: 'Name',
    price: 'Price',
    purchaseDate: 'Purchase Date',
    image: 'Image',
    file: 'File',
    string: 'String',
    boolean: 'Boolean',
    isRequired: 'isRequired',
    pincode: 'Pincode',
    createField: 'Create Field',
    fieldType: 'Field Type',
    selectField: 'Select Field',
    validationType: 'Validation Type',
    addAttributeFor: 'Add attributes for',
    remove: 'Remove',
    addOption: 'Add option',
    description: 'Description',
    addNewField: 'Add New Field',
    addNewFieldGroup: 'Add New FieldGroup',
    minDate: 'minDate',
    maxDate: 'maxDate',
    options: 'options',
    radioOptions: 'radioOptions',
    dropdownOptions: 'dropdownOptions',
    checkboxOptions: 'checkboxOptions',
    multiSelectOptions: 'multiSelectOptions',
    slider: 'slider',
    
  };
  
  export default constants;
  